language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
- nightly
matrix:
  allow_failures:
  - python: nightly
script: python setup.py test
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: nYe/kosb8Yz/YuOfJHvw8ff0GsKTT2P5gRvvqBB/+8entr+UjtW3AuORbUvk3YmMLdzAzhl7xSeP3VfNnl9wZw9Mw0BGwjMo715YRAgLEGk2IGu7IamH0NY/JPi7H1XeASFmQJe0nbugbJjtmgIICCOhw/RoBrth5sV5tzwSl5I=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: coddingtonbear/python-measurement
