language: python
sudo: false
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "nightly"
matrix:
  allow_failures:
  - python: "nightly"
install:
    - pip install -q -e .
script:
    - python setup.py test
